export default [
    "Do you agree or disagree with the statement: Schools should close the computer lab because many students already carry their laptops to school?",
    "Do you agree that employees should have the right to work from home if they wish to? Please include specific details to support your opinion.",
    "Some professors prefer to answer students’ questions at the end of the lecture, and others stop at different points to answer students’ questions. Which style do you think is better for learning?",
    "Some people think with the development of technology and the Internet, libraries will eventually disappear; however, others think libraries are always necessary. Which one do you agree with? Please give specific details to support your opinion.",
    "Suppose two different universities have accepted you. One university is well-known for its excellent academic programs; however, it is expensive; the other university is less well-known, but it offers a full scholarship to pay for your tuition. Which university would you prefer? Explain why.",
    "Some people think that in order to be successful, one has to make enemies. Do you agree or disagree? Explain why.",
    "Do you agree or disagree with the following statement? Children should help their parents with household chores as soon as they are old enough. Use details and examples in your response.",
    "Do you agree or disagree with the following statement? It is better for children to have teachers who are young, even if they are inexperienced.",
    "Do you agree or disagree with the following statement? We can learn a lot from making mistakes.",
    "Some people like to watch news channels on television every day, while others like to watch them only now and then. Which do you prefer? Include details and examples to support your explanation.",
    "Some companies have rules that forbid employees from using personal cell phones during work hours. Do you think this is a good idea? Why or why not? Use specific reasons and examples to support your answer.",
    "Your university plans to restrict the use of the Internet to research only and to no longer allow access to personal e-mail and social media sites on library computers. Do you think this is a good idea? Explain why or why not.",
    "Nowadays, more and more people are using extreme methods, such as surgeries, to change their appearance to look more attractive. Do you think this is a good idea? Support your answer with details and examples.",
    "When traveling in an unfamiliar place, some people prefer to use smartphones or other navigational devices to get around and find places. Others prefer to explore on their own and ask others for directions when necessary. Which do you prefer?",
    "Some people prefer to read physical books made from paper, while others prefer to read electronic books on a digital device. Which do you prefer and why?",
    "Would you prefer to work at one job your entire life or to switch jobs every five years? Explain your response with details and examples.",
    "Do you agree or disagree with the following statement? “Video games have a positive impact on children.” Provide reasons and examples to support your stance.",
    "People learn in different ways. Some people learn by doing, other people learn by reading, and others learn by listening. Which of these methods do you believe is the most effective way to learn? Explain with details and examples.",
    "Some high schools require students to pass a physical fitness exam, in which they are tested on their ability to perform certain physical activities, such as running and swimming, in order to graduate. Do you think this is a good idea?",
    "Some universities expect the students to choose a major field of study when they enter the school; while other universities wait until the second or the third year before students decide to choose a major field of study. Which do you prefer?",
    "Do you agree or disagree with the following statement? “People should be fined when they do not wear masks during a pandemic.” Be sure to use details during your response.",
    "“University students should only use digital textbooks in class.” Do you agree or disagree with the statement? Please give specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Every country should be required to reduce its carbon emissions by at least 25% in the next five years.” Please provide specific details in your argument.",
    "Do you agree or disagree with the following statement: “Robots will replace the majority of jobs in the next decade.” Please include specific details in your argument.",
    "Do you agree or disagree with the following statement? “Students should never ask someone else to help them grammatically correct their research papers.” Be sure to use details during your response.",       
    "“Universities should raise tuition once in a while to support their libraries and other research facilities.” Do you agree or disagree with the statement? Please include specific reasons and details in your answer.",
    "Explain whether you agree or disagree with the following statement: “People who sell illegal drugs should not be sentenced to prison.” Then give specific details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Children should not be allowed to play video games.” Then give specific details in your argument.",
    "“Gasoline-powered cars should be replaced with electric-powered cars.” Do you agree or disagree with the statement? Please include specific reasons and details in your argument.",
    "Do you think it is a government’s responsibility to invest in saving endangered animals or it is non-government organizations’ responsibility to do so?",
    "Do you agree or disagree with the following statement? It is beneficial to watch television on a frequent basis. ",
    "Suppose your sociology professor has asked all students in your class to do a final project – making a presentation. There are two ways :-to give a presentation in class;-to record the presentation as a video file in advance and play the video in class.Which way do you think is better and why? ",
    "Is it better to decide which job to take based on the salary or on the sense of achievement from the job? ",
    "Is the first impression of a person always accurate and reliable? Why or why not? ",
    "Do you think celebrities are responsible for using their money and popularity to help people? ",
    "Do you think machines will replace humans in the future? Please explain your opinion with details and examples. ",
    "Do you agree or disagree with the following statement? To be successful in business, a person should be outgoing and friendly. Please explain your opinion with details and examples. ",
    "Some people believe old people should not take risks and participate in adventurous events as young people. Do you agree or disagree? Why?",
    "Some people would like to borrow money to make a large purchase. Others will save money until they can afford it. Which do you think is a better way and why?",
    "Explain whether you agree or disagree with the following statement: “Countries should ban companies from selling sugary drinks, such as Coca-Cola and Pepsi.” Please include specific details in your argument.",
    "Explain whether you agree or disagree with the following statement: “There is such a thing as love at first sight.”, which means that you can tell in the first 30 seconds of meeting a person whether or not you will be able to fall in love. Please include specific details in your argument.",
    "Do you agree or disagree with the statement? “College students should not be required to take general education courses.” Please include specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Politicians should only be allowed to serve one term, with each term lasting 2 to 4 years.” Please include specific details in your argument.",
    "Explain whether you agree or disagree with the statement. “Honesty is the most important trait in a friend.” Please include specific details in your argument. ",
    "“Children should not be allowed to use virtual reality headsets.” Do you agree or disagree with the statement? Please include specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “All workers should have a guaranteed minimum wage that supports basic quality of life regardless of what skills they possess.” Please include specific details in your argument.",
    "“Writing essays is an effective wage to gauge students’ knowledge.” Explain whether you agree or disagree with the following statement. Please include specific details in your argument.",
    "Do you agree or disagree with the following statement? “Online learning is more effective than traditional classroom learning.” Please include specific details in your argument.",
    "“Teenagers should not be allowed to watch movies with violence and sex.” Do you agree or disagree with the statement? Please include specific details in your argument.",
    "“Teachers’ pay should be based on how much their students are learning.” Explain whether you agree or disagree with the statement. Please include specific details in your argument.",
    "“People older than 65 years old should not be allowed to drive.” Do you agree or disagree with the statement? Please include specific details in your argument.",
    "“Physical libraries should be replaced by online databases and libraries.” Explain whether you agree or disagree with the mentioned statement. Then give specific details in your argument.",
    "“More money should be allocated to academic research projects than to university sports programs.” Explain whether you agree or disagree with the mentioned statement. Then give specific details in your argument.",
    "Some people like to negotiate with merchants to get a lower price when shopping, while other people like to buy things without negotiating. Which do you prefer?",
    " “Even illegal drugs like cocaine and heroin should be legalized with conditions applied.”  Do you agree or disagree with the statement? Please include details and examples in your response.",
    "Do you agree or disagree with the following statement? “Solar power is a better form of energy than wind power.” Please include details and examples in your response.",
    "Do you agree or disagree with the following statement? “It is better to have arranged marriages; that is, the parents determine who their sons and daughters marry.” Please include details and examples in your response.",
    "“No matter the circumstance, you should never tell a lie.” Do you agree or disagree with the statement? Make sure to include specific reasons and supporting details in your argument.",
    "Do you agree or disagree with the following statement? “Countries should spend more money on helping the poor than on exploring outer space.” Please include details and examples in your response.",
    "Do you agree or disagree with the following statement? “The legal driving age should be changed to 21 years old from the current 16 years old requirement.” Please include details and examples in your response.",
    "Do you prefer to study at home or in a library? Please provide specific details to support your explanation.",
    "Do you prefer to run or to walk as your exercise? Illustrate your argument with reasons and supporting details.",
    "Some prefer to travel by planes when visiting a destination 500 to 1,000 kilometers away. Others prefer to travel by train despite the long travel distance. Which do you prefer? Include examples and details to support your answer.",
    "“Some people like having outdoor jobs such as park rangers, construction workers, or sports coaches.  Others prefer to work indoors such as being an accountant, a lawyer, or a doctor. Which type of job would you prefer?  Please include specific details to support your response.",
    "Some students prepare for their tests more effectively in their apartments or off-campus locations, whereas others prefer to prepare in libraries on campus. Which do you prefer? Include examples and details to support your answer.",
    "Do you prefer to work from home on a computer or to work in an office space? Please provide specific details to support your response.",
    "Some prefer electric vehicles as they seem to be more environmentally friendly while others prefer to have gasoline cars. Which would you prefer? Please provide specific details to support your response.",  
    "Some students choose to attend universities close to their homes so that they can still live with their parents, while others attend universities far away from home. Which do you prefer? Please include details and examples to support your answer.",
    "Some people like to watch action movies with violence and drama. Others prefer to watch comedies. Which type of movie do you find more entertaining? Please include details and examples to support your answer.",
    "”Some people like to go to the beach for a vacation, whereas others prefer to go into the mountains for fun. Which do you prefer? Please include details and examples to support your answer.",
    "Do you prefer to go to bed earlier at around 9:00 PM or to stay up until 12:00 AM? Provide specific details to support your explanation.",
    "Do you prefer to buy used cars? Or do you believe that you should always buy a new car? Illustrate your argument with reasons and supporting details.",
    "Some people like to buy new electronic gadgets like smartphones right when the products are newly released, while others will wait a few months before making a purchase. Which do you prefer? Include examples and details to support your answer.",
    "Some students are eager to talk to their professors during office hours when they have questions about course materials. However, others prefer to talk to other students during class when they have questions. Which approach would you prefer? Give some specific details to support your response.",
    "For many, summer is the most favored season of the year, whereas others enjoy the winter time in a year. Which do you prefer? Include examples and details to support your answer.",
    "Do you prefer to live in a climate that has four seasons (i.e., fall, winter, spring, summer) or one that only has one season or similar weather all the time? Please provide specific details to support your explanation.",
    "Some consumers prefer to buy trucks, while others prefer four door sedans. Which do you prefer? Include some examples and details to support your answer.",
    "Some people believe that it is necessary to have a pool when purchasing a house.  However, others prefer not to buy homes with pools. Which view do you support?  Give some specific details to support your response.",
    "Some believe that people who sell illegal drugs should be jailed, whereas others think that these drug dealers should not be imprisoned. What do you think? Include some examples and details to support your answer.",
    "Do you prefer to read printed books? Or do you believe that listening to audiobooks are a better choice? Illustrate your argument with reasons and supporting details.",
    "“Some prefer individual sports such as track and field and cross-country, while others like team sports like basketball and soccer. Which do you prefer? Include examples and details to support your answer.",
    "“Some prefer a diet with meat as the main source of protein. Others prefer to eat vegetarian foods without any meat. Which type of diet do you prefer?  Give specific details to support your response.",      
    "“Some people choose to exercise right after they wake up before going to work, whereas others exercise after work in the evening. Which do you prefer? Include some examples and details to support your answer.",
    "Do you prefer to attend university classes in the morning, afternoon, or in the evening? Provide specific details to support your explanation.",
    "Do you prefer to study alone when you are preparing for a big examination? Or do you believe that studying in a group is a better way to prepare? Illustrate your argument with reasons with supporting details.",
    "Some say children between eight and eleven years of age should be given smartphones, while others believe children at these ages should not be allowed to have smartphones. Which do you prefer? Include examples and details to support your answer.",
    "Some say it is better to remain loyal to one company all their lives. However, others prefer to change jobs frequently throughout their lives. Which view do you support?  Please include specific details to support your response.",
    "Some people believe that a healthy diet is the most important way to stay healthy. Others maintain that exercise is more important. Which opinion do you agree with more? Explain why.",
    "Some people believe that competing against themselves and reaching personal goals while practicing physical activities is beneficial. Others prefer to enjoy and have fun while doing exercises. Which behavior do you think is better?",
    "Some people prefer waking up early while others like to stay in bed for as long as possible in the morning. Which do you prefer? Explain why.",
    "Some people think that price is the most important thing to consider when buying something. Others think that quality is more important. Which do you think is more important and why?",
    "Some people like to spend time with their colleagues outside of work to foster friendships, whilst others choose to keep their social life totally separated from their work life. Which do you think is better? Include details and examples to support your explanation.",
    "Some people believe that there are benefits to failure. Others believe that failures do not yield any benefit. Which view do you agree with and why? Use details and examples to support your response.",      
    "Which of the following qualities do you believe is the most important when it comes to choosing a life partner? HonestyIntelligenceMaturityUse details and examples to support your response.",
    "Which mode of transportation will you choose to go to the office? Private vehicles, public transportation, or taxi service?",
    "Do you agree or disagree that students should start working right after college graduation? Give reasons and examples to support your statement.",
    "Do you agree or disagree that working from home should be a default right of all employees? Please include reasons and examples to support your statement.",
    "Is it better to purchase online or do the shopping offline? Why? Please include reasons and examples to support your statement.",
    "Some believe that brick and mortar stores still exist and have their importance in the future while others believe that there will only be online stores in the future. Which view do you agree with and why? Please include reasons and examples to support your statement.",
    "Should students be encouraged to explore new careers or to follow more traditional career paths? Why? Please include reasons and examples to support your statement."
];

