export default [
    "Do you agree or disagree with the statement: Schools should close the computer lab because many students already carry their laptops to school?",
    "Do you agree that employees should have the right to work from home if they wish to? Please include specific details to support your opinion.",
    "Some professors prefer to answer students’ questions at the end of the lecture, and others stop at different points to answer students’ questions. Which style do you think is better for learning?",
    "Some people think with the development of technology and the Internet, libraries will eventually disappear; however, others think libraries are always necessary. Which one do you agree with? Please give specific details to support your opinion.",
    "Suppose two different universities have accepted you. One university is well-known for its excellent academic programs; however, it is expensive; the other university is less well-known, but it offers a full scholarship to pay for your tuition. Which university would you prefer? Explain why.",
    "Some people think that in order to be successful, one has to make enemies. Do you agree or disagree? Explain why.",
    "Do you agree or disagree with the following statement? Children should help their parents with household chores as soon as they are old enough. Use details and examples in your response.",
    "Do you agree or disagree with the following statement? It is better for children to have teachers who are young, even if they are inexperienced.",
    "Do you agree or disagree with the following statement? We can learn a lot from making mistakes.",
    "Some people like to watch news channels on television every day, while others like to watch them only now and then. Which do you prefer? Include details and examples to support your explanation.",
    "Some companies have rules that forbid employees from using personal cell phones during work hours. Do you think this is a good idea? Why or why not? Use specific reasons and examples to support your answer.",
    "Your university plans to restrict the use of the Internet to research only and to no longer allow access to personal e-mail and social media sites on library computers. Do you think this is a good idea? Explain why or why not.",
    "Nowadays, more and more people are using extreme methods, such as surgeries, to change their appearance to look more attractive. Do you think this is a good idea? Support your answer with details and examples.",
    "When traveling in an unfamiliar place, some people prefer to use smartphones or other navigational devices to get around and find places. Others prefer to explore on their own and ask others for directions when necessary. Which do you prefer?",
    "Some people prefer to read physical books made from paper, while others prefer to read electronic books on a digital device. Which do you prefer and why?",
    "Would you prefer to work at one job your entire life or to switch jobs every five years? Explain your response with details and examples.",
    "Do you agree or disagree with the following statement? “Video games have a positive impact on children.” Provide reasons and examples to support your stance.",
    "People learn in different ways. Some people learn by doing, other people learn by reading, and others learn by listening. Which of these methods do you believe is the most effective way to learn? Explain with details and examples.",
    "Some high schools require students to pass a physical fitness exam, in which they are tested on their ability to perform certain physical activities, such as running and swimming, in order to graduate. Do you think this is a good idea?",
    "Some universities expect the students to choose a major field of study when they enter the school; while other universities wait until the second or the third year before students decide to choose a major field of study. Which do you prefer?",
    "Do you agree or disagree with the following statement? “People should be fined when they do not wear masks during a pandemic.” Be sure to use details during your response.",
    "“University students should only use digital textbooks in class.” Do you agree or disagree with the statement? Please give specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Every country should be required to reduce its carbon emissions by at least 25% in the next five years.” Please provide specific details in your argument.",
    "Do you agree or disagree with the following statement: “Robots will replace the majority of jobs in the next decade.” Please include specific details in your argument.",
    "Do you agree or disagree with the following statement? “Students should never ask someone else to help them grammatically correct their research papers.” Be sure to use details during your response.",
    "“Universities should raise tuition once in a while to support their libraries and other research facilities.” Do you agree or disagree with the statement? Please include specific reasons and details in your answer.",
    "Explain whether you agree or disagree with the following statement: “People who sell illegal drugs should not be sentenced to prison.” Then give specific details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Children should not be allowed to play video games.” Then give specific details in your argument.",
    "“Gasoline-powered cars should be replaced with electric-powered cars.” Do you agree or disagree with the statement? Please include specific reasons and details in your argument.",
    "Do you think it is a government’s responsibility to invest in saving endangered animals or it is non-government organizations’ responsibility to do so?",
    "Do you agree or disagree with the following statement? It is beneficial to watch television on a frequent basis.",
    "Suppose your sociology professor has asked all students in your class to do a final project – making a presentation. There are two ways: to give a presentation in class; to record the presentation as a video file in advance and play the video in class. Which way do you think is better and why?",
    "Is it better to decide which job to take based on the salary or on the sense of achievement from the job?",
    "Is the first impression of a person always accurate and reliable? Why or why not?",
    "Do you think celebrities are responsible for using their money and popularity to help people?",
    "Do you think machines will replace humans in the future? Please explain your opinion with details and examples.",
    "Do you agree or disagree with the following statement? To be successful in business, a person should be outgoing and friendly. Please explain your opinion with details and examples.",
    "Some people believe old people should not take risks and participate in adventurous events as young people. Do you agree or disagree? Why?",
    "Some people would like to borrow money to make a large purchase. Others will save money until they can afford it. Which do you think is a better way and why?",
    "Explain whether you agree or disagree with the following statement: “Countries should ban companies from selling sugary drinks, such as Coca-Cola and Pepsi.” Please include specific details in your argument.",
    "Explain whether you agree or disagree with the following statement: “There is such a thing as love at first sight.”, which means that you can tell in the first 30 seconds of meeting a person whether or not you will be able to fall in love. Please include specific details in your argument.",
    "Do you agree or disagree with the statement? “College students should not be required to take general education courses.” Please include specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “Politicians should only be allowed to serve one term, with each term lasting 2 to 4 years.” Please include specific details in your argument.",
    "Explain whether you agree or disagree with the statement. “Honesty is the most important trait in a friend.” Please include specific details in your argument.",
    "“Children should not be allowed to use virtual reality headsets.” Do you agree or disagree with the statement? Please include specific reasons and supporting details in your argument.",
    "Explain whether you agree or disagree with the following statement: “All workers should have a guaranteed minimum wage that supports basic quality of life regardless of what skills they possess.” Please include specific details in your argument.",
    "“Writing essays is an effective way to gauge students’ knowledge.” Explain whether you agree or disagree with the following statement. Please include specific details in your argument.",
    "Do you agree or disagree with the following statement? “Online learning is more effective than traditional classroom learning.” Please include specific details in your argument.",
    "“Teenagers should not be allowed to watch movies with violence and sex.” Do you agree or disagree with the statement? Please include specific details in your argument.",
    "“Teachers’ pay should be based on how much their students are learning.” Explain whether you agree or disagree with the statement. Please include specific details in your argument.",
    "“People older than 65 years old should not be allowed to drive.” Do you agree or disagree with the statement? Please include specific details in your argument.",
    "“Physical libraries should be replaced by online databases and libraries.” Explain whether you agree or disagree with the mentioned statement. Then give specific details in your argument.",
    "“More money should be allocated to academic research projects than to university sports programs.” Explain whether you agree or disagree with the mentioned statement. Then give specific details in your argument.",
    "Some people like to negotiate with merchants to get a lower price when shopping, while other people like to buy things without negotiating. Which do you prefer?",
    "“Even illegal drugs like cocaine and heroin should be legalized with conditions applied.”  Do you agree or disagree with the statement? Please include details and examples in your response."
];